const Discord = require("discord.js");

module.exports.run = async (bot, msg, args) => {
    msg.channel.sendCode("asciidoc", `=KURALLAR=
=[1](ÇOK ABARTARAK KÜFÜR ETMEK YASAK)
=[2](SPAM YASAK)
=[3](SUNUCUMUZA 2 HAFTA GİRMEYENLER SUNUCUDAN ATILACAK)
=[4](BİRBİRİNİZE SATAŞMAK YASAK)
=[5](SİYASET VE DİN KONULARI HAKKINDA KONUŞMAK YASAKTIR)
=[6](CİNSEL VEYA KAN İÇERİKLİ PAYLAŞIMLAR YAPILMASI YASAKTIR)
=[7](SUNUCUMUZDA HERKES EŞİTTİR)
=[8](IRK DİN AYRIMI YAPMAK KESİNLİKLE YASAKTIR)
=[9](SUNUCUMUZ SOHBET SUNUCUSUDUR)
=[10](SUNUCUMUZDA HER HAFTA TURNUVA DÜZENLENECEKTİR)
=[11](TURNUVADA KAZANANLARA ÖZEL ROLLER VERİLECEKTİR)
=[12](SUNUCU SAHİBİ OLMADIĞI ZAMAN ŞİKAYET VE ÖNERİLERİNİZİ YÖNETİCİYE BİLDİREBİLİRSİNİZ)
=[13](SINIRINI AŞMAMAK ŞEKİLDE İSTEDİĞİNİZİ YAPABİLİRSİNİZ)
=[14](MARKDOWN KULLANIMI YASAKTIR)`
    );
}

module.exports.help = {
    name: "kurallar"
}